# Generated by Django 2.1.7 on 2019-05-24 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada1', models.TimeField()),
                ('saida1', models.TimeField()),
                ('entrada2', models.TimeField(blank=True, null=True)),
                ('saida2', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('entrada1', models.TimeField()),
                ('saida1', models.TimeField(blank=True, null=True)),
                ('entrada2', models.TimeField(blank=True, null=True)),
                ('saida2', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('tipo', models.BooleanField()),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('cargo', models.CharField(max_length=64)),
                ('chefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ponto.Chefe')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ponto.Configuracoes')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ponto.Funcionario'),
        ),
    ]
